POST http://localhost:3003/api/blogs
content-type: application/json

{
    "title": "Fourth blog",
    "author": "C. blog4",
    "url": "http://blog4",
    "likes": 1
}

###
GET http://localhost:3003/api/blogs/
