POST http://localhost:3003/api/blogs
content-type: application/json

{
    "title": "New blog3",
    "author": "New author3",
    "url": "http://blog33",
    "likes": 3
}

###
POST http://localhost:3003/api/users
Content-Type: application/json

{
   "username": "aminu3",
   "name": "aminu33",
   "password": "3333" 
}

###
GET http://localhost:3003/api/blogs/


###
DELETE http://localhost:3003/api/blogs/692c7d8533b8aa15b64c7aac

###
UPDATE http://localhost:3003/api/blogs/691a35bd4919c7dede708409

{
    "title": "Another blog",
    "author": "C. blog4",
    "url": "http://blog4",
    "likes": 12
}

###
POST http://localhost:3003/api/login
Content-Type: application/json

{
    "username": "aminu1",
    "password": "1111"
}